Repository FarGroup/FarManager, pull requests merged in 2021-03, with the labels that each got.

#372 Add GitHub actions workflow
  .github/workflows/far-build.yml
Labels: enhancement

#373 HlfChecker compares references in paragraphs.
  far/FarEng.hlf.m4
  far/FarHun.hlf.m4
  far/FarPol.hlf.m4
  far/FarRus.hlf.m4
  misc/hlf-checker/HlfChecker.cmd
  misc/hlf-checker/HlfChecker.linq
Labels: enhancement, translation

#375 Update FarPol.hlf.m4
  far/FarPol.hlf.m4
Labels: translation

#376 Update farlang.templ.m4
  far/farlang.templ.m4
Labels: translation

#377 Update FarPol.hlf.m4
  far/FarPol.hlf.m4
Labels: translation
