Repository FarGroup/FarManager, pull requests merged in 2021-12, with the labels that each got.

#487 fix mantis 3910
  plugins/network/NetBel.hlf
  plugins/network/NetClass.cpp
  plugins/network/NetClass.hpp
  plugins/network/NetCze.hlf
  plugins/network/NetEng.hlf
  plugins/network/NetGer.hlf
  plugins/network/NetHun.hlf
  plugins/network/NetPol.hlf
  plugins/network/NetRus.hlf
  plugins/network/NetSky.hlf
  plugins/network/NetUkr.hlf
  plugins/network/Network.cpp
  plugins/network/changelog
  plugins/network/version.hpp
Labels: bug, enhancement

#491 Mantis#0003921 command 'cd' in network panel
  plugins/network/NetClass.cpp
  plugins/network/changelog
  plugins/network/version.hpp
Labels: bug

#494 Update CasePol.hlf
  plugins/filecase/CasePol.hlf
Labels: translation

#420 LuaMacro: more introspection with mf.EnumScripts
  enc/enc_lua/macroapi_manual.en.tsi
  enc/enc_lua/macroapi_manual.ru.tsi
  plugins/luamacro/_globalinfo.lua
  plugins/luamacro/api.lua
  plugins/luamacro/changelog
  plugins/luamacro/lang.lua
  plugins/luamacro/lm_bel.lng
  plugins/luamacro/lm_eng.lng
  plugins/luamacro/lm_ita.lng
  plugins/luamacro/lm_pol.lng
  plugins/luamacro/lm_rus.lng
  plugins/luamacro/lm_sky.lng
  plugins/luamacro/lm_spa.lng
  plugins/luamacro/luafar/version.h
  plugins/luamacro/mbrowser.lua
  plugins/luamacro/panelsort.lua
  plugins/luamacro/utils.lua
Labels: enhancement

#497 refactoring
  plugins/network/NetClass.cpp
  plugins/network/NetClass.hpp
  plugins/network/NetCommon.cpp
  plugins/network/NetCommon.hpp
  plugins/network/NetFavorites.cpp
  plugins/network/NetFavorites.hpp
  plugins/network/Network.cpp
  plugins/network/changelog
  plugins/network/version.hpp
Labels: enhancement
